Rails Group Capstone Project 🚀
DevKaranJ/recipes pull request #21
Opened 2024-02-10 16:09 UTC by evansnyamekye

# Features we completed in this Capstone 

You should follow the layout of the wireframes provided. You should personalize the rest of the design including colors, typographies, spacings, etc.

- Login page and registration page:

Should be built with Devise.

- Recipes list:

Should display a list of recipes created by the logged-in user as in the wireframe.
Should lead to recipe details.

- Public recipe list:

Should display a list of all public recipes ordered by newest as in the wireframe.
Should lead to recipe details.
If the user is the owner of the recipe, should allow the user to delete it.

- Recipe details:

Should display a toggle button that allows for a recipe to be made public or private.
If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
Make sure there are no N+1 queries happening.

Create a navigation menu that allows users to open all of the pages you created.

- Write unit and integration tests

Only for a group that has less than 3 members:

- Food list:

Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
Should lead to a form that allows users to add new food.
General shopping list view:
Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
Should count the total food items and total price of the missing food.
If your team has 3 members these are requirements; otherwise, they are additional requirements

- Inventories list:

Should display a list of inventories created by the logged-in user as in the wireframe.
Should lead to inventory details.
If the user is the owner of the inventory, should allow to delete it.

- Inventory details:

Should display the inventory details as in the wireframe.
Should lead to a form that allows users to add new food.

- Recipe details:

Should have a modal to choose an inventory to create a shopping list with, as in the wireframe.

- Inventory shopping list:

Should show the list of food that is missing by comparing the food in the recipe with the food in the inventory.
Should count the total food items and total price of the missing food.

- Technical setup

Set up the repository on GitHub and use Gitflow.
Set up Devise for authentication.
Set up RSpec and Capybara testing libraries.

@DevKaranJ 
@evansnyamekye 
@newtonah0 

Thank you 😃.

2024-02-10 18:35 UTC, skyv26 requested changes
## Hi @evansnyamekye , @DevKaranJ and @newtonah0, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTljYjFhMDZmNmM4MTA2ZmNlOGEzY2E1ZjE5OWM3MDc5NzM5MGE0MyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/2sGZ6lqDkf1HW1q0sk/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Well-structured project ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-10 18:35 UTC, skyv26 commented on app/views/users/index.html.erb
> +    <%= form_with(model: current_user, url: update_name_path, method: :patch) do |form| %>
- [ ] Please make sure that your application is working fine, it seems like the `update_name_path` doesn't exist in your routes. It should be actually `user_update_name_path` which further requires the `user_id`. I noticed this problem while creating a new user or `registering` a user. Kindly fix the issue and make sure that your application is working fine without any errors.

![image](https://github.com/DevKaranJ/recipes/assets/66476329/5c01dd4b-d6a5-43f6-97d4-f6fd0679914d)

2024-02-10 18:35 UTC, skyv26 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Kindly add the `:confirmable` callback which will help the user to confirm their account after `registering` it with the email ID because in this way it will make sure that the user is `genuine` or `authentic` and then allow that user to `use` the resources like creating, updating or `deleting` the recipe, food etc.

2024-02-10 18:35 UTC, skyv26 commented on app/views/foods/index.html.erb
- [ ] Kindly adhere to the project requirements in your case you didn't add the `Add Food` button, on your `page`. By clicking the button, a user should be able to add `food`. Kindly add the `button` and make sure that your functionality should work as expected.

## Requirement
![image](https://github.com/DevKaranJ/recipes/assets/66476329/c21cbcfe-66b3-464f-bf33-aabdd3676bc9)


## Wireframe Design
![food_index](https://github.com/DevKaranJ/recipes/assets/66476329/49795ce1-3ef9-4cf5-948e-c8eb2d6c4b37)

## Your Design
![image](https://github.com/DevKaranJ/recipes/assets/66476329/26298fa1-c976-479d-9b28-13ee3f4c3d60)

2024-02-10 18:35 UTC, skyv26 commented on app/views/recipes/show.html.erb
> +    <p>Public: <%= @recipe.public ? 'Yes' : 'No' %></p>
- [ ] Please follow the `wireframe` properly, as per the wireframe, you should add a `toggle` button, which allows the user to change the `recipe` visibility from `public` to `private` or vice-versa. Implementing the small details will help you to become a `detail-oriented` developer. Kindly add the toggle button and make sure that it should be functional as well.

## Requirement
![image](https://github.com/DevKaranJ/recipes/assets/66476329/b5a48c40-45d3-43c5-b6d3-fa3aa5f022f8)


## Wireframe
![recipe_food](https://github.com/DevKaranJ/recipes/assets/66476329/4f902639-4d6f-4e3a-aa37-845142842513)

## Your Design
![image](https://github.com/DevKaranJ/recipes/assets/66476329/c705424d-24cf-496d-a5f5-3db260e8a3f7)

2024-02-10 18:35 UTC, skyv26 commented on app/views/public_recipes/index.html.erb
> +    <p>Total Value: <%= total_quantity %></p>
- [ ] Please follow the wirefreame properly, because as I can see that your `wireframe` layout for the `recipe` card is not matching with the given design in the wireframe,

## Actual Design
![image](https://github.com/DevKaranJ/recipes/assets/66476329/355edde5-1a86-4c3f-8caa-2f4845f11885)

## Your Design
![image](https://github.com/DevKaranJ/recipes/assets/66476329/4be94b47-1346-45d6-8b8c-5b007724e54d)

2024-02-10 18:35 UTC, skyv26 commented on app/views/inventories/show.html.erb
> +</div>
- [ ] Your design should match with the `wireframe` as I mentioned earlier, it seems like you missed the basic styling to achieve the `wireframe` design. Kindly make your `detail` page according to the design provided in the requirement.

## Design should look like

![image](https://github.com/DevKaranJ/recipes/assets/66476329/28befb18-3136-4b2a-b429-19da75e88708)

## Your Design
![image](https://github.com/DevKaranJ/recipes/assets/66476329/309587ed-eff9-49b1-a33a-d31f731a8e85)

2024-02-10 18:35 UTC, skyv26 commented on app/views/recipes/show.html.erb
> +    <%= link_to "Generate Shopping List (Coming Soon)", "#", class: "btn btn-primary disabled" %>
- [ ] Kindly adhere to the project requirement, it seems like you didn't implement the `inventory shopping list` feature in your project, according to which you should use the shopping list button, which further opens a `popup` menu for creating the inventory shopping list. Please focus more on the requirement and implement things accordingly, don't forget to implement the feature as it looks in the wireframe image below.

### Requirement
![image](https://github.com/DevKaranJ/recipes/assets/66476329/22ba95fb-ba74-486e-9e71-8121effcb73e)

![image](https://github.com/DevKaranJ/recipes/assets/66476329/3a012d09-586e-4b9a-a932-939598886396)


- [ ] Please also provide a shopping list page in your application as it is given in the wireframe.

![inventory_shopping_list](https://github.com/DevKaranJ/recipes/assets/66476329/cfed3a92-f16c-46b0-9cc5-8e3c50eb409c)

2024-02-10 18:35 UTC, skyv26 commented on app/models/user.rb
> +  has_many :foods
- [ ] Please make sure that you established the `association` correctly, it seems like your `association` is not correct. Kindly take a look again at the `ERD` diagram and implement the association properly. If you try to understand you will find that `food` itself is an independent entity regardless of user which is a part of `many` inventories or `recipes` through the join table.

![recipe_erd](https://github.com/DevKaranJ/recipes/assets/66476329/4a4b6196-bf8b-4b42-8f2c-10c6dfad05b6)

2024-02-10 18:35 UTC, skyv26 commented on app/models/recipe.rb
> +  has_many :recipe_foods
- [ ] Please also fix the `association` here, I encourage you to understand the ERD diagram properly and brainstorm with your partner about it.

2024-02-10 18:35 UTC, skyv26 commented on app/models/food.rb
- [ ] Please do the same here

2024-02-10 18:35 UTC, skyv26 commented on app/models/inventory_food.rb
- [ ] Please also fix the `association` here, I encourage you to understand the ERD diagram properly and brainstorm with your partner about it.

2024-02-10 23:16 UTC, 1GORDON requested changes
##
## Hi @DevKaranJ, @evansnyamekye, and @newtonah0 ✋

Good job so far!

## Highlights!
- Implemented requested changes ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-10 23:16 UTC, 1GORDON commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
Hello team 🤝
- As requested by the previous reviewer, kindly add the :confirmable callback which will help the user to confirm their account after registering it with the email ID because in this way it will make sure that the user is genuine or authentic and then allow that user to use the resources like creating, updating or deleting the recipe, food etc.

2024-02-12 08:13 UTC, bellom commented
Hi Team,

#### This is a manual review

Great job adding confirmable. The CR did well requesting this change.

### Approved

2024-02-12 10:51 UTC, merged